### ISSUE TITLE
adjustment for vesion 7

### ISSUE THREAD

**Issue by diabetic0** [q77190858/zotero-pdf-background#16]
i would appreciate it if you can adapt version 7 of zotero.

**Comment by Singal0927** [comment]
附议

**Comment by MontelukastNa** [comment]
+1

**Comment by wangth2001** [comment]
+1

**Comment by haohaoxiao** [comment]
+1

**Comment by JzHuai0108** [comment]
+1

**Comment by JzHuai0108** [comment]
Apparently, to make this plugin work for zotero 7, we need to go through the following steps.
1. the codebase source code needs a major overhaul from zotero 6 to zotero 7 as detailed [here](https://www.zotero.org/support/dev/zotero_7_for_developers).
I think this step will take 2 days for an experienced developer but not familiar with zotero or firefox.

2. build the release xpi file as described [here](https://github.com/windingwind/zotero-plugin-template#quick-start-guide).
I think this step will take 1 day for an experienced developer.

3. If you don't need the xpi file, you may install the plugin from source as described [here](https://www.zotero.org/support/dev/client_coding/plugin_development), instead of step 2.

[Reference](https://forums.zotero.org/discussion/105825/how-to-develop-a-zotero-7-plugin)

**Comment by CrashBugger** [comment]
+1 , other plugins are too slow and heavy!

**Comment by chuanjin-su** [comment]
附议

**Comment by MicReed** [comment]
附议

**Comment by q77190858** [comment]
have adjusted.
